name: Check and deploy project 

on: 
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Checks

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: Install deps
      run: yarn install
    - name: Check with eslint
      run: yarn lint
    - name: Run tests
      if: always()
      run: yarn test
    - name: Run e2e tests
      if: always()
      run: yarn test:e2e
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    
    needs: [test]
    
    steps: 
    - uses: actions/checkout@v2
    - if: github.ref == 'refs/heads/main'
      run: echo "run deploy"
